### ISSUE TITLE
Editor lives own life

### ISSUE THREAD

**Issue by StalkAlex** [dmstr/yii2-prototype-module#4]
Hello. A little question about editor. Is there any way to get back an old one? Because new one is not working properly. I am trying to edit one of my template, I need to add this html code

```
<barcode code="Your message here" size="0.8" type="QR" error="M" class="barcode" />
```

I am doing it on source tab, I'm adding it, clicking save. It's in database, but It vanishes from editor when I am trying to edit it again, editor just hides this line even if I wrap it with div tags.

Found `allowedContent` attribute to disable filtration, but this code not work

```
<?= $form->field($model, 'value')->widget(CKEditor::className(), [
                'options' => ['height' => '400', 'allowedContent' => true ],
                'preset' => 'full',
            ]) ?>
```

**Comment by schmunk42** [comment]
You should be able to override the `_form` view with standard Yii 2 configuration (aliases, path maps).

But a property for the editor type would also be nice for the module, PRs always welcome.
