### ISSUE TITLE
Access for non-Editor users

### ISSUE THREAD

**Issue by david-sa** [dmstr/yii2-prototype-module#6]
Hi. Maybe I have misunderstood something but it seems that the HtmlWidget renders the content just when the user have the 'Editor' role (which has 'Pages Module', 'Main Site Controller' and 'Backend Dashboard' permissions).

```
const ACCESS_ROLE = 'Editor';
...
 if (\Yii::$app->user->can(self::ACCESS_ROLE)) {
```

Shouldn't this code:

```
if (!$model) {
    $html = $this->renderEmpty();
} else {
    $html = $model->value;
}
```

be out of the `user->can(self::ACCESS_ROLE)` check?

Otherwise I don't have clear how to use the module to make pages publicly available.

**Comment by david-sa** [comment]
Even better:

```
if ($model) {
    $html = $model->value;
}
```

An Editor doesn't need `$this->renderEmpty()` because the link is already available in the Flash message and, if the user is not an Editor, it shouldn't see it.

Also, as a side note, but also regarding HtmlWidget, we have:

```
if ($this->enableBackendMenuItem) {
    \Yii::$app->params['backend.menuItems'][] = [
        'label' => 'Edit HTML',
        'url' => ($model) ? $this->generateEditRoute($model->id) : $this->generateCreateRoute()
    ];
}
```

As you know, `params` are not really meant to be altered because it does not persist across different requests so, IMHO, are not the place to store this kind of things. I saw the implementation of `Yii::$app->params['backend.menuItems'][]` in yii2-backend-module and, even when is a cool idea, it becomes a little messy.

Thank you!

**Comment by schmunk42** [comment]
Thank you for your feedback!
