### ISSUE TITLE
Make twigs available as file

### ISSUE THREAD

**Issue by schmunk42** [dmstr/yii2-prototype-module#7]
By using the **key** under a certain alias, like:

```
@twig/my-triple.twig     
@twig/my-triple.db-twig
```

Requires a CLI command to write files to disk.

**Comment by eluhr** [comment]
https://github.com/dmstr/yii2-prototype-module/commit/f62d7a265c65d32409d3c56b22d33adc50575929

prototype/export-twig --escapeFileNames=1 --exportPath=@twig

**Comment by eluhr** [comment]
Is that a workable solution? Has the issue been resolved with this solution?

**Comment by schmunk42** [comment]
I think so, we need to wire this into the setup process, but that's a different task.
